---
abstract: 'Retrieves the CPAN Top100 data from http://ali.as/top100'
author:
  - 'Apocalypse <APOCAL@cpan.org>'
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-WWW-Top100-Retrieve
provides:
  CPAN::WWW::Top100::Retrieve:
    file: lib/CPAN/WWW/Top100/Retrieve.pm
    version: 0.01
  CPAN::WWW::Top100::Retrieve::Dist:
    file: lib/CPAN/WWW/Top100/Retrieve/Dist.pm
    version: 0.01
  CPAN::WWW::Top100::Retrieve::Utils:
    file: lib/CPAN/WWW/Top100/Retrieve/Utils.pm
    version: 0.01
requires:
  HTML::TableExtract: 0
  LWP::UserAgent: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::StrictConstructor: 0
  Params::Coerce: 0
  URI: 0
  namespace::autoclean: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CPAN-WWW-Top100-Retrieve
  homepage: http://search.cpan.org/dist/CPAN-WWW-Top100-Retrieve
  license: http://dev.perl.org/licenses/
  repository: http://github.com/apocalypse/perl-cpan-www-top100-retrieve
version: 0.01
